require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'TW' do
  use_unimodules!(exclude: [
            'expo-face-detector',
            'expo-constants',
            'expo-permissions',
            'expo-app-loader-provider',
            'unimodules-barcode-scanner-interface',
            'unimodules-camera-interface',
            'unimodules-constants-interface',
            'unimodules-face-detector-interface',
            'unimodules-sensors-interface',
            'unimodules-task-manager-interface'
    ])
    
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'TWTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' })

  # pods for icons

  post_install do |installer|
     react_native_post_install(installer)
     # exclude arm64 arch - only if you're building in m1
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
         end
     end
   end
end
